### ISSUE TITLE
LIBERTY = LIFE

### ISSUE THREAD

**Issue by bettie-borgia** [liberty-x/lxriddle#2]
DEAR LIBErTY X!

I AM AN ECC_EN_TRIC BILLIONAIRE AND SERIAL WIDOW LOOKING TO ACQUIRE MORE ODDITIES AND MOneY-MAKERS FOR MY P-O-R-T-F-O-L-I-O.

I AM WILLING TO EXCHANGE **CLIENt-MANAGEMENT AND PIVOTAL TRACKER TRAINGING** IN EXCHANGE FOR A CONTROLLING STAKE IN THE PROJECT

I WOULD REQUIRE A MEETING AS SOON AS POSSIBLE

**Comment by Jbarget** [comment]
LibertyX
Santander

09-01-32
84624536

speak soon...

**Comment by bettie-borgia** [comment]
THE DOWN PAYMENT HAS BEEN MADE.

MAY I ASSUME ...

# YOU ACCEPT MY DEAL?

**Comment by Jbarget** [comment]
What % share are you after?

**Comment by bettie-borgia** [comment]
88%

**Comment by Jbarget** [comment]
We can do no more than 92%

**Comment by Jbarget** [comment]
Do you accept?

**Comment by bettie-borgia** [comment]
# ACCEPTED :new_moon::fire::new_moon::fire::new_moon::fire::new_moon::fire::new_moon::fire::new_moon::fire::new_moon::fire::new_moon::fire::new_moon::fire::new_moon::fire::new_moon::fire::new_moon::fire:
