### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by rjmk** [liberty-x/lxriddle#24]
Loving the structure, guys! Backend could have a folder as well. You can still leave your bootstrap file (`server.js`) in the root

**Comment by hdrdavies** [comment]
Awesome! Do you have a name you normally give a folder containing all JS files? We read in a couple of places that stuffing all JS files in a directory is a sensible thing to do (agree? / disagree?)

**Comment by rjmk** [comment]
I wouldn't structure things that way. I prefer a backend and a frontend folder. Perhaps that was advice for structuring a non-node project? `api` is a fairly common name for a backend folder, but `backend` is fine too.
