### ISSUE TITLE
lx-iife

### ISSUE THREAD

**Issue by rjmk** [liberty-x/lxriddle#26]
Using an IIFE is not necessary here: https://github.com/liberty-x/lxriddle/blob/4986b44a068d2e1a89b31dbdac7670a0017abfc4/handler.js#L1

That's a technique for having module-like code organisation when not using something like the node module system. Variables declared in one file will not be transferred to a file that requires it unless they are explicitly exported.

**Comment by hdrdavies** [comment]
Cool. We're looking to edit this tonight.

**Comment by hdrdavies** [comment]
@rjmk Will be fixed after my pull request is merged

**Comment by rjmk** [comment]
:+1:
