### ISSUE TITLE
password visible

### ISSUE THREAD

**Issue by rub1e** [liberty-x/lxriddle#31]
https://github.com/liberty-x/lxriddle/blob/master/public/login.html#L18

The password is visible. I won't insult you by _giving_ you the answer, but you can find it here: https://developer.mozilla.org/en/docs/Web/HTML/Element/Input

I bloody love the look of this though - seriously good work!

**Comment by hdrdavies** [comment]
Thanks Ruby :heart: 

Will fix this now

**Comment by hdrdavies** [comment]
Will be done after the next pull request @rub1e

**Comment by mk4111** [comment]
still not fixed maayyyn.
