### ISSUE TITLE
MONOCHROME = BUSY

### ISSUE THREAD

**Issue by bettie-borgia** [liberty-x/lxriddle#5]
THE AMOUNT OF DIFFERENT SHADES ON YOUR WIREFRAMES IS MAKING ME SICK!!!!!

**Comment by bettie-borgia** [comment]
# GENIES: FOR MY FIRST WISH, I WANT YOU TO MAKE THE BACKGROUND AND THE TEXT THE EXACT SAME SHADE OF GREY

**Comment by rjmk** [comment]
Oh dear, guys. It looks like you might have gotten in over your heads ...

Take this, you may need it: www.pivotaltracker.com

**Comment by hdrdavies** [comment]
I'm super glad we resolve this in our M-E-E-T-I-N-G earlier! LoL! :+1: :8ball:
