### ISSUE TITLE
MODES OF COMMUNICATION

### ISSUE THREAD

**Issue by bettie-borgia** [liberty-x/lxriddle#6]
PLEASE SEE THE MESSAGE I HAVE LEFT YOU IN _CITY GARDENING VOL. 3_ IN THE HACKNEY LIBRARY REGARDING THE FUTURE OF THIS PROJECT

ALSO PLZ SPEAK TO MY ART TEACHER MR PRINCEVIL FOR MY SUGGESTED UPDATES TO THE WIREFRAMES

PLZ PROVIDE ME WITH YOUR SEMAPHORE ADDRESS

**Comment by rjmk** [comment]
I would suggest organising a client meeting ASAP ...

**Comment by hdrdavies** [comment]
![address](https://files.gitter.im/RachelBLondon/libert-x/KjkX/rsz_screenshot_from_2015-10-14_125252-_1_.png)

**Comment by hdrdavies** [comment]
Could we meet at the above address in 5 minutes?

**Comment by bettie-borgia** [comment]
I can't do 5 minutes from then as I have the funeral for my 16th husband and then my 17th husband and I are going bungee jumping. Are you free 5 minutes from now?

**Comment by bettie-borgia** [comment]
Also, we will have to make efficient use of my time as my pet penguin has an interview with the ghost writer of its uplifting and upcoming autobiography _Living with Being Taxidermi'd_

**Comment by hdrdavies** [comment]
yeah come down then Rafe

**Comment by Jbarget** [comment]
WHO ARE YOU!!!!

http://www.deathfigures.com/index.php?id=Bo-6094484

**Comment by bettie-borgia** [comment]
a lover, a friend, a companion....who are you ?

**Comment by hdrdavies** [comment]
Great! Look forward to hearing from you on PiVoTaL TrAcKeR! :eggplant:
