### ISSUE TITLE
Script injection code still in database

### ISSUE THREAD

**Issue by RachBLondon** [liberty-x/lxriddle#64]
I noticed this :
%3Cstyle%3E body %7Bbackground-image: url(%22http:

%3Cdiv style=%22position:fixed; left:0; top:0;height:1000000000000000000000px; width:1000000000000000000000px; background-color:red;%22 class=%22splash%22%3E %3Cimg class=%22image-logo%22 src=%22https:

**Comment by hdrdavies** [comment]
feeling nostalgic @RachBLondon ?

:wink:
